version: "3.1"

services:
  wordpress:
    container_name: wp
    build:
      context: ./build
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: test123
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: test123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - mysql
  wpcli:
    image: wordpress:cli-2
    volumes:
      - .:/var/www/html
    depends_on:
      - wordpress
    user: "33:33"
    entrypoint: wp
volumes:
  db-data:
